In [12]:
import numpy as np
import pandas as pd

In [13]:
filename="connecticut-history.csv"
fileURl = "https://covidtracking.com/data/download/"

dfCT = pd.read_csv(fileURl+filename)


filename1="colorado-history.csv"
fileURl = "https://covidtracking.com/data/download/"

dfCO = pd.read_csv(fileURl+filename1)

In [14]:
# 1  the number of rows of data, and the number of columns for connecticut
rows, columns=dfCT.shape
print("number of rows of data:",rows)
print("number of columns:", columns)
print(dfCT.head(3))
print(dfCT.tail(3))
print(dfCT.head(3).T)
print(dfCT.tail(3).T)

number of rows of data: 373
number of columns: 41
         date state   death  deathConfirmed  deathIncrease  deathProbable  \
0  2021-03-07    CT  7704.0          6327.0              0         1377.0
1  2021-03-06    CT  7704.0          6327.0              0         1377.0
2  2021-03-05    CT  7704.0          6327.0             11         1377.0

   hospitalized  hospitalizedCumulative  hospitalizedCurrently  \
0       12257.0                 12257.0                  428.0
1       12257.0                 12257.0                  428.0
2       12257.0                 12257.0                  428.0

   hospitalizedIncrease  ...  totalTestResults  totalTestResultsIncrease  \
0                     0  ...           6520366                         0
1                     0  ...           6520366                         0
2                     0  ...           6520366                     41868

   totalTestsAntibody  totalTestsAntigen  totalTestsPeopleAntibody  \
0                 NaN           396680.0                       NaN
1                 NaN           396680.0                       NaN
2                 NaN           396680.0                       NaN

   totalTestsPeopleAntigen  totalTestsPeopleViral  \
0                      NaN                    NaN
1                      NaN                    NaN
2                      NaN                    NaN

   totalTestsPeopleViralIncrease  totalTestsViral  totalTestsViralIncrease
0                              0          6520366                        0
1                              0          6520366                        0
2                              0          6520366                    41868

[3 rows x 41 columns]
           date state  death  deathConfirmed  deathIncrease  deathProbable  \
370  2020-03-02    CT    NaN             NaN              0            NaN
371  2020-03-01    CT    NaN             NaN              0            NaN
372  2020-02-29    CT    NaN             NaN              0            NaN

     hospitalized  hospitalizedCumulative  hospitalizedCurrently  \
370           NaN                     NaN                    NaN
371           NaN                     NaN                    NaN
372           NaN                     NaN                    NaN

     hospitalizedIncrease  ...  totalTestResults  totalTestResultsIncrease  \
370                     0  ...                 8                         4
371                     0  ...                 4                         1
372                     0  ...                 3                         0

     totalTestsAntibody  totalTestsAntigen  totalTestsPeopleAntibody  \
370                 NaN                NaN                       NaN
371                 NaN                NaN                       NaN
372                 NaN                NaN                       NaN

     totalTestsPeopleAntigen  totalTestsPeopleViral  \
370                      NaN                    NaN
371                      NaN                    NaN
372                      NaN                    NaN

     totalTestsPeopleViralIncrease  totalTestsViral  totalTestsViralIncrease
370                              0                8                        4
371                              0                4                        1
372                              0                3                        3

[3 rows x 41 columns]
                                           0           1           2
date                              2021-03-07  2021-03-06  2021-03-05
state                                     CT          CT          CT
death                                   7704        7704        7704
deathConfirmed                          6327        6327        6327
deathIncrease                              0           0          11
deathProbable                           1377        1377        1377
hospitalized                           12257       12257       12257
hospitalizedCumulative                 12257       12257       12257
hospitalizedCurrently                    428         428         428
hospitalizedIncrease                       0           0           0
inIcuCumulative                          NaN         NaN         NaN
inIcuCurrently                           NaN         NaN         NaN
negative                                 NaN         NaN         NaN
negativeIncrease                           0           0           0
negativeTestsAntibody                    NaN         NaN         NaN
negativeTestsPeopleAntibody              NaN         NaN         NaN
negativeTestsViral                   6188566     6188566     6188566
onVentilatorCumulative                   NaN         NaN         NaN
onVentilatorCurrently                    NaN         NaN         NaN
positive                              285330      285330      285330
positiveCasesViral                    265709      265709      265709
positiveIncrease                           0           0         830
positiveScore                              0           0           0
positiveTestsAntibody                    NaN         NaN         NaN
positiveTestsAntigen                   22245       22245       22245
positiveTestsPeopleAntibody              NaN         NaN         NaN
positiveTestsPeopleAntigen               NaN         NaN         NaN
positiveTestsViral                    323284      323284      323284
recovered                                NaN         NaN         NaN
totalTestEncountersViral                 NaN         NaN         NaN
totalTestEncountersViralIncrease           0           0           0
totalTestResults                     6520366     6520366     6520366
totalTestResultsIncrease                   0           0       41868
totalTestsAntibody                       NaN         NaN         NaN
totalTestsAntigen                     396680      396680      396680
totalTestsPeopleAntibody                 NaN         NaN         NaN
totalTestsPeopleAntigen                  NaN         NaN         NaN
totalTestsPeopleViral                    NaN         NaN         NaN
totalTestsPeopleViralIncrease              0           0           0
totalTestsViral                      6520366     6520366     6520366
totalTestsViralIncrease                    0           0       41868
                                         370         371         372
date                              2020-03-02  2020-03-01  2020-02-29
state                                     CT          CT          CT
death                                    NaN         NaN         NaN
deathConfirmed                           NaN         NaN         NaN
deathIncrease                              0           0           0
deathProbable                            NaN         NaN         NaN
hospitalized                             NaN         NaN         NaN
hospitalizedCumulative                   NaN         NaN         NaN
hospitalizedCurrently                    NaN         NaN         NaN
hospitalizedIncrease                       0           0           0
inIcuCumulative                          NaN         NaN         NaN
inIcuCurrently                           NaN         NaN         NaN
negative                                 NaN         NaN         NaN
negativeIncrease                           0           0           0
negativeTestsAntibody                    NaN         NaN         NaN
negativeTestsPeopleAntibody              NaN         NaN         NaN
negativeTestsViral                         8           4           3
onVentilatorCumulative                   NaN         NaN         NaN
onVentilatorCurrently                    NaN         NaN         NaN
positive                                 NaN         NaN         NaN
positiveCasesViral                       NaN         NaN         NaN
positiveIncrease                           0           0           0
positiveScore                              0           0           0
positiveTestsAntibody                    NaN         NaN         NaN
positiveTestsAntigen                     NaN         NaN         NaN
positiveTestsPeopleAntibody              NaN         NaN         NaN
positiveTestsPeopleAntigen               NaN         NaN         NaN
positiveTestsViral                         0           0           0
recovered                                NaN         NaN         NaN
totalTestEncountersViral                 NaN         NaN         NaN
totalTestEncountersViralIncrease           0           0           0
totalTestResults                           8           4           3
totalTestResultsIncrease                   4           1           0
totalTestsAntibody                       NaN         NaN         NaN
totalTestsAntigen                        NaN         NaN         NaN
totalTestsPeopleAntibody                 NaN         NaN         NaN
totalTestsPeopleAntigen                  NaN         NaN         NaN
totalTestsPeopleViral                    NaN         NaN         NaN
totalTestsPeopleViralIncrease              0           0           0
totalTestsViral                            8           4           3
totalTestsViralIncrease                    4           1           3

In [15]:
# 1  the number of rows of data, and the number of columns for colorado
rows, columns=dfCO.shape
print("number of rows of data:",rows)
print("number of columns:", columns)
print(dfCO.head(3))
print(dfCO.tail(3))
print(dfCO.head(3).T)
print(dfCO.tail(3).T)

number of rows of data: 369
number of columns: 41
         date state   death  deathConfirmed  deathIncrease  deathProbable  \
0  2021-03-07    CO  5989.0          5251.0              3          735.0
1  2021-03-06    CO  5986.0          5251.0              0          735.0
2  2021-03-05    CO  5986.0          5250.0             12          736.0

   hospitalized  hospitalizedCumulative  hospitalizedCurrently  \
0       23904.0                 23904.0                  326.0
1       23886.0                 23886.0                  326.0
2       23863.0                 23863.0                  356.0

   hospitalizedIncrease  ...  totalTestResults  totalTestResultsIncrease  \
0                    18  ...         6415123.0                     38163
1                    23  ...         6376960.0                     33600
2                    72  ...         6343360.0                     33127

   totalTestsAntibody  totalTestsAntigen  totalTestsPeopleAntibody  \
0            435053.0                NaN                       NaN
1            433082.0                NaN                       NaN
2            430938.0                NaN                       NaN

   totalTestsPeopleAntigen  totalTestsPeopleViral  \
0                      NaN              2616541.0
1                      NaN              2610434.0
2                      NaN              2604007.0

   totalTestsPeopleViralIncrease  totalTestsViral  totalTestsViralIncrease
0                           6107              NaN                        0
1                           6427              NaN                        0
2                           6312              NaN                        0

[3 rows x 41 columns]
           date state  death  deathConfirmed  deathIncrease  deathProbable  \
366  2020-03-06    CO    NaN             NaN              0            NaN
367  2020-03-05    CO    NaN             NaN              0            NaN
368  2020-03-04    CO    NaN             NaN              0            NaN

     hospitalized  hospitalizedCumulative  hospitalizedCurrently  \
366           NaN                     NaN                    NaN
367           NaN                     NaN                    NaN
368           NaN                     NaN                    NaN

     hospitalizedIncrease  ...  totalTestResults  totalTestResultsIncrease  \
366                     0  ...               NaN                         0
367                     0  ...               NaN                         0
368                     0  ...               NaN                         0

     totalTestsAntibody  totalTestsAntigen  totalTestsPeopleAntibody  \
366                 NaN                NaN                       NaN
367                 NaN                NaN                       NaN
368                 NaN                NaN                       NaN

     totalTestsPeopleAntigen  totalTestsPeopleViral  \
366                      NaN                    NaN
367                      NaN                    NaN
368                      NaN                    NaN

     totalTestsPeopleViralIncrease  totalTestsViral  totalTestsViralIncrease
366                              0              NaN                        0
367                              0              NaN                        0
368                              0              NaN                        0

[3 rows x 41 columns]
                                            0            1            2
date                               2021-03-07   2021-03-06   2021-03-05
state                                      CO           CO           CO
death                                    5989         5986         5986
deathConfirmed                           5251         5251         5250
deathIncrease                               3            0           12
deathProbable                             735          735          736
hospitalized                            23904        23886        23863
hospitalizedCumulative                  23904        23886        23863
hospitalizedCurrently                     326          326          356
hospitalizedIncrease                       18           23           72
inIcuCumulative                           NaN          NaN          NaN
inIcuCurrently                            NaN          NaN          NaN
negative                              2199458      2199458      2193953
negativeIncrease                            0         5505         5212
negativeTestsAntibody                  369995       368326       366328
negativeTestsPeopleAntibody               NaN          NaN          NaN
negativeTestsViral                        NaN          NaN          NaN
onVentilatorCumulative                    NaN          NaN          NaN
onVentilatorCurrently                     NaN          NaN          NaN
positive                               436602       435762       434654
positiveCasesViral                     410976       410976       410054
positiveIncrease                          840         1108         1633
positiveScore                               0            0            0
positiveTestsAntibody                   63087        62612        61933
positiveTestsAntigen                      NaN          NaN          NaN
positiveTestsPeopleAntibody               NaN          NaN          NaN
positiveTestsPeopleAntigen                NaN          NaN          NaN
positiveTestsViral                        NaN          NaN          NaN
recovered                                 NaN          NaN          NaN
totalTestEncountersViral          6.41512e+06  6.37696e+06  6.34336e+06
totalTestEncountersViralIncrease        38163        33600        33127
totalTestResults                  6.41512e+06  6.37696e+06  6.34336e+06
totalTestResultsIncrease                38163        33600        33127
totalTestsAntibody                     435053       433082       430938
totalTestsAntigen                         NaN          NaN          NaN
totalTestsPeopleAntibody                  NaN          NaN          NaN
totalTestsPeopleAntigen                   NaN          NaN          NaN
totalTestsPeopleViral             2.61654e+06  2.61043e+06  2.60401e+06
totalTestsPeopleViralIncrease            6107         6427         6312
totalTestsViral                           NaN          NaN          NaN
totalTestsViralIncrease                     0            0            0
                                         366         367         368
date                              2020-03-06  2020-03-05  2020-03-04
state                                     CO          CO          CO
death                                    NaN         NaN         NaN
deathConfirmed                           NaN         NaN         NaN
deathIncrease                              0           0           0
deathProbable                            NaN         NaN         NaN
hospitalized                             NaN         NaN         NaN
hospitalizedCumulative                   NaN         NaN         NaN
hospitalizedCurrently                    NaN         NaN         NaN
hospitalizedIncrease                       0           0           0
inIcuCumulative                          NaN         NaN         NaN
inIcuCurrently                           NaN         NaN         NaN
negative                                  55          46          19
negativeIncrease                           9          27           0
negativeTestsAntibody                    NaN         NaN         NaN
negativeTestsPeopleAntibody              NaN         NaN         NaN
negativeTestsViral                       NaN         NaN         NaN
onVentilatorCumulative                   NaN         NaN         NaN
onVentilatorCurrently                    NaN         NaN         NaN
positive                                   8           2           2
positiveCasesViral                       NaN         NaN         NaN
positiveIncrease                           6           0           0
positiveScore                              0           0           0
positiveTestsAntibody                    NaN         NaN         NaN
positiveTestsAntigen                     NaN         NaN         NaN
positiveTestsPeopleAntibody              NaN         NaN         NaN
positiveTestsPeopleAntigen               NaN         NaN         NaN
positiveTestsViral                       NaN         NaN         NaN
recovered                                NaN         NaN         NaN
totalTestEncountersViral                 NaN         NaN         NaN
totalTestEncountersViralIncrease           0           0           0
totalTestResults                         NaN         NaN         NaN
totalTestResultsIncrease                   0           0           0
totalTestsAntibody                       NaN         NaN         NaN
totalTestsAntigen                        NaN         NaN         NaN
totalTestsPeopleAntibody                 NaN         NaN         NaN
totalTestsPeopleAntigen                  NaN         NaN         NaN
totalTestsPeopleViral                    NaN         NaN         NaN
totalTestsPeopleViralIncrease              0           0           0
totalTestsViral                          NaN         NaN         NaN
totalTestsViralIncrease                    0           0           0

In [16]:
#2a Are there any columns that have ALL NaNs?
print("Are there any columns that have ALL NaNs in connecticut-history.csv :",dfCT.isnull().values.any())
print("Are there any columns that have ALL NaNs in colorado-history.csv :",dfCO.isnull().values.any())

Are there any columns that have ALL NaNs in connecticut-history.csv : True
Are there any columns that have ALL NaNs in colorado-history.csv : True

In [17]:
#2b Columns having ALL NaNs in connecticut
print("Columns which have all NaNs for connecticut\n", dfCO.isnull().all(axis=0)[lambda x:x])

Columns which have all NaNs for connecticut
 inIcuCumulative                True
inIcuCurrently                 True
negativeTestsPeopleAntibody    True
negativeTestsViral             True
onVentilatorCumulative         True
onVentilatorCurrently          True
positiveTestsAntigen           True
positiveTestsPeopleAntibody    True
positiveTestsPeopleAntigen     True
positiveTestsViral             True
recovered                      True
totalTestsAntigen              True
totalTestsPeopleAntibody       True
totalTestsPeopleAntigen        True
totalTestsViral                True
dtype: bool

In [18]:
print("Columns which have all NaNs for colorado\n", dfCO.isnull().all(axis=0)[lambda x:x])

Columns which have all NaNs for colorado
 inIcuCumulative                True
inIcuCurrently                 True
negativeTestsPeopleAntibody    True
negativeTestsViral             True
onVentilatorCumulative         True
onVentilatorCurrently          True
positiveTestsAntigen           True
positiveTestsPeopleAntibody    True
positiveTestsPeopleAntigen     True
positiveTestsViral             True
recovered                      True
totalTestsAntigen              True
totalTestsPeopleAntibody       True
totalTestsPeopleAntigen        True
totalTestsViral                True
dtype: bool

In [19]:
#3a Number of non NaN values of each row in connecticut-history.csv
dfCT = dfCT.T
A = dfCT.dropna(axis='columns', how='all')
c =A.count()
print("the number of non-Nan values for each row in connecticut\n",A.count())
print("the maximum of these numbers is ", A.count().max())

#3b  rows having maximum number of values in connecticut
print("rows having maximum number of values in connecticut",(c == A.count().max()).sum())

the number of non-Nan values for each row in connecticut
 0      25
1      25
2      25
3      25
4      25
       ..
368    15
369    15
370    15
371    15
372    15
Length: 373, dtype: int64
the maximum of these numbers is  25
rows having maximum number of values in connecticut 122

In [20]:
#3a Number of non NaN values of each row in colorado-history.csv
dfCO = dfCO.T
A = dfCO.dropna(axis='columns', how='all')
d =A.count()
print("the number of non-Nan values for each row in colorado\n",A.count())
print("the maximum of these numbers is ", A.count().max())

#3b rows having maximum number of values in colorado
print("rows having maximum number of values in colorado",(d == A.count().max()).sum())

the number of non-Nan values for each row in colorado
 0      26
1      26
2      26
3      26
4      26
       ..
364    13
365    13
366    13
367    13
368    13
Length: 369, dtype: int64
the maximum of these numbers is  26
rows having maximum number of values in colorado 297

In [21]:
#4a Number of non NaN values of each row in connecticut-history.csv
A = dfCT.dropna(axis='columns', how='all')
c =A.count()
print("the number of non-Nan values for each row in connecticut\n",A.count())
print("the minimum of these numbers is ", A.count().min())

#4b  rows having minimum number of values in connecticut
print("rows having minimum number of values in connecticut",(c == c.min()).sum())

the number of non-Nan values for each row in connecticut
 0      25
1      25
2      25
3      25
4      25
       ..
368    15
369    15
370    15
371    15
372    15
Length: 373, dtype: int64
the minimum of these numbers is  15
rows having minimum number of values in connecticut 7

In [22]:
#4a Number of non NaN values of each row in colorado-history.csv
dfCO_notNaN = dfCO.dropna(axis='columns', how='all')
d =dfCO_notNaN.count()
print("the number of non-Nan values for each row\n",d)
print("the minimum of these numbers is ", d.min())

#4b rows having minimum number of values
print("rows having minumum number of values",(d == d.min()).sum())

the number of non-Nan values for each row
 0      26
1      26
2      26
3      26
4      26
       ..
364    13
365    13
366    13
367    13
368    13
Length: 369, dtype: int64
the minimum of these numbers is  13
rows having minumum number of values 7